### ISSUE TITLE
Шрифт, положение и шаблон подписей к рисункам 

### ISSUE THREAD

**Issue by dead142** [RoyalCat/EasyModelManager#1]
Ответ 

> Наименование таблицы, при ее наличии, должно   отражать ее содержание, быть точным, кратким.

Верный ответ

> выравнивание по центру; пишется ключевое слово "Рисунок" далее номер, дефис и название рисунка с большой буквы:
Рисунок 1 – Название рисунка

P.S. Отчет оформляется одним файлом)

**Comment by royalcat** [comment]
Исправил, в отдельной ветке, одобрено?
